services:
  postgres:
    image: postgis/postgis:16-3.4
    container_name: checksalary-db
    environment:
      POSTGRES_DB: checksalary
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: CheckSalary/Dockerfile
    container_name: checksalary-api
    ports:
      - "5067:5067"
    environment:
      - ConnectionStrings__Postgres=Host=postgres;Port=5432;Database=checksalary;Username=admin;Password=password123
      - ConnectionStrings__Redis=redis:6379
      - ConnectionStrings__RabbitMQ=rabbitmq://rabbitmq
      - Jaeger__Endpoint=http://jaeger:4317
      - Ollama__BaseUrl=http://host.docker.internal:11434
    depends_on:
      - postgres
      - redis
      - rabbitmq

  redis:
    image: redis:7-alpine
    container_name: checksalary-redis
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: checksalary-rabbit
    ports:
      - "5672:5672"
      - "15672:15672"

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: checksalary-jaeger
    ports:
      - "16686:16686"
      - "4317:4317"

volumes:
  pgdata: